// Code generated by protoc-gen-zmicro-gin. DO NOT EDIT.
// versions:
// - protoc-gen-zmicro-gin v0.2.0
// - protoc                v4.24.0
// source: api/hello.proto

package api

import (
	context "context"
	errors "errors"
	gin "github.com/gin-gonic/gin"
	http "github.com/zmicro-team/zmicro/core/transport/http"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = errors.New
var _ = context.TODO
var _ = gin.New

// GreeterHTTPServer
type GreeterHTTPServer interface {
	// SayHello
	SayHello(context.Context, *HelloRequest, *HelloReply) error
}

func RegisterGreeterHTTPServer(g *gin.RouterGroup, srv GreeterHTTPServer) {
	r := g.Group("")
	{
		r.GET("/hello/:name", _Greeter_SayHello0_HTTP_Handler(srv))
	}
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		carrier := http.FromCarrier(c.Request.Context())
		shouldBind := func(req *HelloRequest) error {
			if err := c.ShouldBindQuery(req); err != nil {
				return err
			}
			if err := c.ShouldBindUri(req); err != nil {
				return err
			}
			return carrier.Validate(c.Request.Context(), req)
		}

		var err error
		var req HelloRequest
		var reply *HelloReply = new(HelloReply)

		if err = shouldBind(&req); err != nil {
			carrier.ErrorBadRequest(c, err)
			return
		}
		err = srv.SayHello(c.Request.Context(), &req, reply)
		if err != nil {
			carrier.Error(c, err)
			return
		}
		carrier.Render(c, reply)
	}
}
