// Code generated by "stringer -type=Env -linecomment"; DO NOT EDIT.

package env

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Develop-1]
	_ = x[Testing-2]
	_ = x[Staging-3]
	_ = x[Product-4]
}

const _Env_name = "NoneDevelopTestingStagingProduct"

var _Env_index = [...]uint8{0, 4, 11, 18, 25, 32}

func (i Env) String() string {
	if i < 0 || i >= Env(len(_Env_index)-1) {
		return "Env(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Env_name[_Env_index[i]:_Env_index[i+1]]
}
